name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        # Tests need access to system packages (for dbus-python)
        os: [
            "ubuntu-22.04", # Python 3.10, BlueZ 5.64, dbus-python 1.2.18
            "ubuntu-24.04", # Python 3.12, BlueZ 5.72, dbus-python 1.3.2
            "ubuntu-26.04", # Python 3.14, BlueZ 5.85, dbus-python 1.4.0
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: make .venv
      - name: Run lint
        run: make lint
      - name: Run typecheck
        run: make typecheck
      - name: Run tests
        run: make test
